### PR TITLE
Update arithmetic.hpp to extend unit_vector to non-Cartesian representation

### PR DESCRIPTION
**Pull request by nitink25**
### Description

Updated arithmetic.hpp to generalize unit_vector function for all representations. Previously it was wriiten only for Cartesian.

### CODE REVIEW

**Review by lpranam — CHANGES_REQUESTED** [review]
You also need to add test for the same please check test files there are some commented tests

https://github.com/BoostGSoC19/astronomy/blob/develop/test/coordinate/spherical_representation.cpp
https://github.com/BoostGSoC19/astronomy/blob/develop/test/coordinate/spherical_equatorial_representation.cpp

**Comment by nitink25** [comment]
> You also need to add test for the same please check test files there are some commented tests
> 
> https://github.com/BoostGSoC19/astronomy/blob/develop/test/coordinate/spherical_representation.cpp
> https://github.com/BoostGSoC19/astronomy/blob/develop/test/coordinate/spherical_equatorial_representation.cpp

Will work on it.

**Review by lpranam — APPROVED** [review]
Everything looks good. Thank you for your contribution.

**Comment by lpranam** [comment]
closes #82

**Pull request merged**
